import ts from "typescript";

const _ResponseHandlerAST = (context: ts.TransformationContext) => {
  return context.factory.createClassDeclaration(undefined, context.factory.createIdentifier("_ResponseHandler"), undefined, undefined, [
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("callbackWaitsForEmptyEventLoop"),
      undefined,
      context.factory.createKeywordTypeNode(ts.SyntaxKind.BooleanKeyword),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("functionVersion"),
      undefined,
      context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("functionName"),
      undefined,
      context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("memoryLimitInMB"),
      undefined,
      context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("logGroupName"),
      undefined,
      context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("logStreamName"),
      undefined,
      context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("clientContext"),
      undefined,
      context.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("identity"),
      undefined,
      context.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("invokedFunctionArn"),
      undefined,
      context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("awsRequestId"),
      undefined,
      context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("getRemainingTimeInMillis"),
      undefined,
      context.factory.createFunctionTypeNode(undefined, [], context.factory.createKeywordTypeNode(ts.SyntaxKind.NumberKeyword)),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("succeed"),
      undefined,
      context.factory.createFunctionTypeNode(
        undefined,
        [
          context.factory.createParameterDeclaration(
            undefined,
            undefined,
            context.factory.createIdentifier("responseContent"),
            undefined,
            context.factory.createIntersectionTypeNode([
              context.factory.createTypeReferenceNode(context.factory.createIdentifier("RawResponseContent"), undefined),
              context.factory.createTypeReferenceNode(context.factory.createIdentifier("Object"), undefined),
            ]),
            undefined
          ),
        ],
        context.factory.createKeywordTypeNode(ts.SyntaxKind.VoidKeyword)
      ),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createPrivateIdentifier("#succeed"),
      undefined,
      context.factory.createFunctionTypeNode(
        undefined,
        [
          context.factory.createParameterDeclaration(
            undefined,
            undefined,
            context.factory.createIdentifier("responseContent"),
            undefined,
            context.factory.createIntersectionTypeNode([
              context.factory.createTypeReferenceNode(context.factory.createIdentifier("RawResponseContent"), undefined),
              context.factory.createTypeReferenceNode(context.factory.createIdentifier("Object"), undefined),
            ]),
            undefined
          ),
        ],
        context.factory.createKeywordTypeNode(ts.SyntaxKind.VoidKeyword)
      ),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("done"),
      undefined,
      context.factory.createFunctionTypeNode(
        undefined,
        [
          context.factory.createParameterDeclaration(
            undefined,
            undefined,
            context.factory.createIdentifier("error"),
            undefined,
            context.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
            undefined
          ),
          context.factory.createParameterDeclaration(
            undefined,
            undefined,
            context.factory.createIdentifier("responseContent"),
            undefined,
            context.factory.createIntersectionTypeNode([
              context.factory.createTypeReferenceNode(context.factory.createIdentifier("RawResponseContent"), undefined),
              context.factory.createTypeReferenceNode(context.factory.createIdentifier("Object"), undefined),
            ]),
            undefined
          ),
        ],
        context.factory.createKeywordTypeNode(ts.SyntaxKind.VoidKeyword)
      ),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createPrivateIdentifier("#done"),
      undefined,
      context.factory.createFunctionTypeNode(
        undefined,
        [
          context.factory.createParameterDeclaration(
            undefined,
            undefined,
            context.factory.createIdentifier("error"),
            undefined,
            context.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
            undefined
          ),
          context.factory.createParameterDeclaration(
            undefined,
            undefined,
            context.factory.createIdentifier("responseContent"),
            undefined,
            context.factory.createIntersectionTypeNode([
              context.factory.createTypeReferenceNode(context.factory.createIdentifier("RawResponseContent"), undefined),
              context.factory.createTypeReferenceNode(context.factory.createIdentifier("Object"), undefined),
            ]),
            undefined
          ),
        ],
        context.factory.createKeywordTypeNode(ts.SyntaxKind.VoidKeyword)
      ),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("fail"),
      undefined,
      context.factory.createFunctionTypeNode(
        undefined,
        [
          context.factory.createParameterDeclaration(
            undefined,
            undefined,
            context.factory.createIdentifier("error"),
            undefined,
            context.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
            undefined
          ),
        ],
        context.factory.createKeywordTypeNode(ts.SyntaxKind.VoidKeyword)
      ),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createPrivateIdentifier("#fail"),
      undefined,
      context.factory.createFunctionTypeNode(
        undefined,
        [
          context.factory.createParameterDeclaration(
            undefined,
            undefined,
            context.factory.createIdentifier("error"),
            undefined,
            context.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
            undefined
          ),
        ],
        context.factory.createKeywordTypeNode(ts.SyntaxKind.VoidKeyword)
      ),
      undefined
    ),
    context.factory.createPropertyDeclaration(undefined, context.factory.createIdentifier("isSent"), undefined, undefined, context.factory.createFalse()),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createIdentifier("locals"),
      undefined,
      undefined,
      context.factory.createObjectLiteralExpression([], false)
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createPrivateIdentifier("#responseObject"),
      undefined,
      context.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
      undefined
    ),
    context.factory.createPropertyDeclaration(
      undefined,
      context.factory.createPrivateIdentifier("#resolve"),
      undefined,
      context.factory.createTypeReferenceNode(context.factory.createIdentifier("Function"), undefined),
      undefined
    ),
    context.factory.createConstructorDeclaration(
      undefined,
      [
        context.factory.createParameterDeclaration(
          undefined,
          undefined,
          context.factory.createIdentifier("param"),
          undefined,
          context.factory.createTypeReferenceNode(context.factory.createIdentifier("param"), undefined),
          undefined
        ),
      ],
      context.factory.createBlock(
        [
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#responseObject")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createObjectLiteralExpression(
                [
                  context.factory.createPropertyAssignment(context.factory.createIdentifier("statusCode"), context.factory.createNumericLiteral("200")),
                  context.factory.createPropertyAssignment(context.factory.createIdentifier("headers"), context.factory.createObjectLiteralExpression([], false)),
                ],
                false
              )
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#resolve")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("resolve2"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("callbackWaitsForEmptyEventLoop")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("callbackWaitsForEmptyEventLoop"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("functionVersion")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("functionVersion"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("functionName")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("functionName"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("memoryLimitInMB")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("memoryLimitInMB"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("clientContext")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("clientContext"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("identity")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("identity"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("invokedFunctionArn")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("invokedFunctionArn"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("awsRequestId")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("awsRequestId"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("getRemainingTimeInMillis")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("getRemainingTimeInMillis"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#succeed")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("succeed"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#done")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("done"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#fail")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createPropertyAccessExpression(context.factory.createIdentifier("param"), context.factory.createIdentifier("fail"))
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("succeed")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createArrowFunction(
                undefined,
                undefined,
                [
                  context.factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    context.factory.createIdentifier("responseContent"),
                    undefined,
                    context.factory.createIntersectionTypeNode([
                      context.factory.createTypeReferenceNode(context.factory.createIdentifier("RawResponseContent"), undefined),
                      context.factory.createTypeReferenceNode(context.factory.createIdentifier("Object"), undefined),
                    ]),
                    undefined
                  ),
                ],
                context.factory.createKeywordTypeNode(ts.SyntaxKind.VoidKeyword),
                context.factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                context.factory.createBlock(
                  [
                    context.factory.createExpressionStatement(
                      context.factory.createCallExpression(
                        context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#succeed")),
                        undefined,
                        [context.factory.createIdentifier("responseContent")]
                      )
                    ),
                  ],
                  true
                )
              )
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("done")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createArrowFunction(
                undefined,
                undefined,
                [
                  context.factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    context.factory.createIdentifier("error"),
                    undefined,
                    context.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
                    undefined
                  ),
                  context.factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    context.factory.createIdentifier("responseContent"),
                    undefined,
                    context.factory.createIntersectionTypeNode([
                      context.factory.createTypeReferenceNode(context.factory.createIdentifier("RawResponseContent"), undefined),
                      context.factory.createTypeReferenceNode(context.factory.createIdentifier("Object"), undefined),
                    ]),
                    undefined
                  ),
                ],
                undefined,
                context.factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                context.factory.createBlock(
                  [
                    context.factory.createExpressionStatement(
                      context.factory.createCallExpression(
                        context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#done")),
                        undefined,
                        [context.factory.createIdentifier("error"), context.factory.createIdentifier("responseContent")]
                      )
                    ),
                  ],
                  true
                )
              )
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("fail")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createArrowFunction(
                undefined,
                undefined,
                [
                  context.factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    context.factory.createIdentifier("error"),
                    undefined,
                    context.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
                    undefined
                  ),
                ],
                context.factory.createKeywordTypeNode(ts.SyntaxKind.VoidKeyword),
                context.factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                context.factory.createBlock(
                  [
                    context.factory.createExpressionStatement(
                      context.factory.createCallExpression(
                        context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#fail")),
                        undefined,
                        [context.factory.createIdentifier("error")]
                      )
                    ),
                  ],
                  true
                )
              )
            )
          ),
        ],
        true
      )
    ),
    context.factory.createMethodDeclaration(
      undefined,
      undefined,
      context.factory.createPrivateIdentifier("#returnReseponse"),
      undefined,
      undefined,
      [],
      undefined,
      context.factory.createBlock(
        [
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("isSent")),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createTrue()
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createCallExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#resolve")),
              undefined,
              [context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#responseObject"))]
            )
          ),
        ],
        true
      )
    ),
    context.factory.createMethodDeclaration(
      undefined,
      undefined,
      context.factory.createIdentifier("status"),
      undefined,
      undefined,
      [
        context.factory.createParameterDeclaration(
          undefined,
          undefined,
          context.factory.createIdentifier("code"),
          undefined,
          context.factory.createKeywordTypeNode(ts.SyntaxKind.NumberKeyword),
          context.factory.createNumericLiteral("200")
        ),
      ],
      undefined,
      context.factory.createBlock(
        [
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(
                context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#responseObject")),
                context.factory.createIdentifier("statusCode")
              ),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createIdentifier("code")
            )
          ),
          context.factory.createReturnStatement(context.factory.createThis()),
        ],
        true
      )
    ),
    context.factory.createMethodDeclaration(
      undefined,
      undefined,
      context.factory.createIdentifier("set"),
      undefined,
      undefined,
      [
        context.factory.createParameterDeclaration(
          undefined,
          undefined,
          context.factory.createIdentifier("key"),
          undefined,
          context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
          undefined
        ),
        context.factory.createParameterDeclaration(
          undefined,
          undefined,
          context.factory.createIdentifier("value"),
          undefined,
          context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
          undefined
        ),
      ],
      undefined,
      context.factory.createBlock(
        [
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createElementAccessExpression(
                context.factory.createPropertyAccessExpression(
                  context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#responseObject")),
                  context.factory.createIdentifier("headers")
                ),
                context.factory.createIdentifier("key")
              ),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createIdentifier("value")
            )
          ),
          context.factory.createReturnStatement(context.factory.createThis()),
        ],
        true
      )
    ),
    context.factory.createMethodDeclaration(
      undefined,
      undefined,
      context.factory.createIdentifier("type"),
      undefined,
      undefined,
      [
        context.factory.createParameterDeclaration(
          undefined,
          undefined,
          context.factory.createIdentifier("contentType"),
          undefined,
          context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
          undefined
        ),
      ],
      undefined,
      context.factory.createBlock(
        [
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createElementAccessExpression(
                context.factory.createPropertyAccessExpression(
                  context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#responseObject")),
                  context.factory.createIdentifier("headers")
                ),
                context.factory.createStringLiteral("content-type")
              ),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createIdentifier("contentType")
            )
          ),
          context.factory.createReturnStatement(context.factory.createThis()),
        ],
        true
      )
    ),
    context.factory.createMethodDeclaration(
      undefined,
      undefined,
      context.factory.createIdentifier("cookie"),
      undefined,
      undefined,
      [
        context.factory.createParameterDeclaration(
          undefined,
          undefined,
          context.factory.createIdentifier("name"),
          undefined,
          context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
          undefined
        ),
      ],
      undefined,
      context.factory.createBlock([context.factory.createReturnStatement(context.factory.createThis())], true)
    ),
    context.factory.createMethodDeclaration(
      undefined,
      undefined,
      context.factory.createIdentifier("clearCookie"),
      undefined,
      undefined,
      [
        context.factory.createParameterDeclaration(
          undefined,
          undefined,
          context.factory.createIdentifier("name"),
          undefined,
          context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
          undefined
        ),
      ],
      undefined,
      context.factory.createBlock([context.factory.createReturnStatement(context.factory.createThis())], true)
    ),
    context.factory.createMethodDeclaration(
      undefined,
      undefined,
      context.factory.createIdentifier("json"),
      undefined,
      undefined,
      [
        context.factory.createParameterDeclaration(
          undefined,
          undefined,
          context.factory.createIdentifier("body"),
          undefined,
          context.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
          undefined
        ),
      ],
      undefined,
      context.factory.createBlock(
        [
          context.factory.createExpressionStatement(
            context.factory.createCallExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("type")),
              undefined,
              [context.factory.createStringLiteral("application/json")]
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(
                context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#responseObject")),
                context.factory.createIdentifier("body")
              ),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createCallExpression(
                context.factory.createPropertyAccessExpression(context.factory.createIdentifier("JSON"), context.factory.createIdentifier("stringify")),
                undefined,
                [context.factory.createIdentifier("body")]
              )
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createCallExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#returnReseponse")),
              undefined,
              []
            )
          ),
        ],
        true
      )
    ),
    context.factory.createMethodDeclaration(
      undefined,
      undefined,
      context.factory.createIdentifier("send"),
      undefined,
      undefined,
      [
        context.factory.createParameterDeclaration(
          undefined,
          undefined,
          context.factory.createIdentifier("content"),
          undefined,
          context.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
          undefined
        ),
      ],
      undefined,
      context.factory.createBlock(
        [
          context.factory.createExpressionStatement(
            context.factory.createBinaryExpression(
              context.factory.createPropertyAccessExpression(
                context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#responseObject")),
                context.factory.createIdentifier("body")
              ),
              context.factory.createToken(ts.SyntaxKind.EqualsToken),
              context.factory.createIdentifier("content")
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createCallExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#returnReseponse")),
              undefined,
              []
            )
          ),
        ],
        true
      )
    ),
    context.factory.createMethodDeclaration(
      undefined,
      undefined,
      context.factory.createIdentifier("redirect"),
      undefined,
      undefined,
      [
        context.factory.createParameterDeclaration(
          undefined,
          undefined,
          context.factory.createIdentifier("code"),
          undefined,
          context.factory.createKeywordTypeNode(ts.SyntaxKind.NumberKeyword),
          undefined
        ),
        context.factory.createParameterDeclaration(
          undefined,
          undefined,
          context.factory.createIdentifier("path"),
          undefined,
          context.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
          undefined
        ),
      ],
      undefined,
      context.factory.createBlock(
        [
          context.factory.createExpressionStatement(
            context.factory.createCallExpression(
              context.factory.createPropertyAccessExpression(
                context.factory.createCallExpression(
                  context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createIdentifier("status")),
                  undefined,
                  [context.factory.createIdentifier("code")]
                ),
                context.factory.createIdentifier("set")
              ),
              undefined,
              [context.factory.createStringLiteral("Location"), context.factory.createIdentifier("path")]
            )
          ),
          context.factory.createExpressionStatement(
            context.factory.createCallExpression(
              context.factory.createPropertyAccessExpression(context.factory.createThis(), context.factory.createPrivateIdentifier("#returnReseponse")),
              undefined,
              []
            )
          ),
        ],
        true
      )
    ),
  ]);
};

export { _ResponseHandlerAST };
